### ISSUE TITLE
NPE crash in ResourcesUtil.getIdString()

### ISSUE THREAD

**Issue by rickbrew** [facebook/stetho#131]
Looks like we *do* need to check for null after all

```
java.lang.NullPointerException
    at com.facebook.stetho.common.android.ResourcesUtil.getIdString(ResourcesUtil.java:41)
    at com.facebook.stetho.common.android.ResourcesUtil.getIdStringQuietly(ResourcesUtil.java:24)
    at com.facebook.stetho.inspector.elements.android.ViewDescriptor.getIdAttribute(ViewDescriptor.java:40)
    at com.facebook.stetho.inspector.elements.android.ViewDescriptor.onCopyAttributes(ViewDescriptor.java:28)
    at com.facebook.stetho.inspector.elements.android.ViewDescriptor.onCopyAttributes(ViewDescriptor.java:14)
    at com.facebook.stetho.inspector.elements.ChainedDescriptor.copyAttributes(ChainedDescriptor.java:133)
    at com.facebook.stetho.inspector.protocol.module.DOM.createNodeForElement(DOM.java:159)
    at com.facebook.stetho.inspector.protocol.module.DOM.getChildNodesForElement(DOM.java:175)
    at com.facebook.stetho.inspector.protocol.module.DOM.createNodeForElement(DOM.java:155)
    at com.facebook.stetho.inspector.protocol.module.DOM.getChildNodesForElement(DOM.java:175)
    at com.facebook.stetho.inspector.protocol.module.DOM.createNodeForElement(DOM.java:155)
    at com.facebook.stetho.inspector.protocol.module.DOM.getChildNodesForElement(DOM.java:175)
    at com.facebook.stetho.inspector.protocol.module.DOM.createNodeForElement(DOM.java:155)
    at com.facebook.stetho.inspector.protocol.module.DOM.getChildNodesForElement(DOM.java:175)
    at com.facebook.stetho.inspector.protocol.module.DOM.createNodeForElement(DOM.java:155)
    at com.facebook.stetho.inspector.protocol.module.DOM.getChildNodesForElement(DOM.java:175)
    at com.facebook.stetho.inspector.protocol.module.DOM.createNodeForElement(DOM.java:155)
    at com.facebook.stetho.inspector.protocol.module.DOM.getChildNodesForElement(DOM.java:175)
    at com.facebook.stetho.inspector.protocol.module.DOM.createNodeForElement(DOM.java:155)
    at com.facebook.stetho.inspector.protocol.module.DOM.access$400(DOM.java:42)
    at com.facebook.stetho.inspector.protocol.module.DOM$1.run(DOM.java:80)
    at com.facebook.stetho.common.android.HandlerUtil$WaitableRunnable.run(HandlerUtil.java:45)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5579)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rickbrew** [comment]
@jasta
