### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Tolriq** [facebook/stetho#140]
Seems stetho 1.1 now works for the element view but requires more reflexion meaning all proguarded app will crash : 

```
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: getId []
            at com.facebook.stetho.common.ReflectionUtil.getMethod(ReflectionUtil.java:45)
            at com.facebook.stetho.common.android.FragmentApi$ReflectionFragmentAccessor.<init>(FragmentApi.java:157)
            at com.facebook.stetho.common.android.FragmentApi.<clinit>(FragmentApi.java:44)
            at com.facebook.stetho.inspector.elements.android.FragmentDescriptor.register(FragmentDescriptor.java:21)
```

It would be interesting to have an update of the documentation for all the needed (and correct) proguard configuration.

For my needs I use a simple :

```
-keep class com.facebook.stetho.** {*;}
-keepclassmembers public class * {
   *** get*();
}
```

But a smarter and proper configuration would be way better.

**Comment by jasta** [comment]
This was very unfortunate that we solved the problem this way and are
looking at revisit our use of reflection here.  It was not required and can
be addressed cleanly.

**Comment by jasta** [comment]
I've corrected the problem that required new proguard rules in the first place, but I agree we should document that proguard rules are required for basic functionality.  I think the Wiki is the right place for this, with a rearranged web site to better highlight those entries.  Hopefully we can address that soon.

**Comment by jasta** [comment]
Finally dealt with this.

That said, #80 points out that we still have a need for some better documentation in this area.  I'm going to look at starting a wiki document for common issues.
