### ISSUE TITLE
NoSuchMethodException when accessing 'getFragmentManager' for 'android.support.v4.app.Fragment'

### ISSUE THREAD

**Issue by hungryTux** [facebook/stetho#146]
I see the following crash on version 1.1.0.
```
E  FATAL EXCEPTION: StethoWorker30
                        E  java.lang.ExceptionInInitializerError
                        E      at com.facebook.stetho.inspector.elements.android.FragmentDescriptor.register(FragmentDescriptor.java:21)
                        E      at com.facebook.stetho.inspector.elements.android.AndroidDOMProvider.<init>(AndroidDOMProvider.java:53)
                        E      at com.facebook.stetho.inspector.elements.android.AndroidDOMProviderFactory.create(AndroidDOMProviderFactory.java:19)
                        E      at com.facebook.stetho.inspector.protocol.module.DOM$PeerManagerListener.onFirstPeerRegistered(DOM.java:201)
                        E      at com.facebook.stetho.inspector.helper.PeersRegisteredListener.onPeerRegistered(PeersRegisteredListener.java:24)
                        E      at com.facebook.stetho.inspector.helper.ChromePeerManager.addPeer(ChromePeerManager.java:77)
                        E      at com.facebook.stetho.inspector.protocol.module.DOM.enable(DOM.java:63)
                        E      at java.lang.reflect.Method.invokeNative(Native Method)
                        E      at java.lang.reflect.Method.invoke(Method.java:511)
                        E      at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:98)
                        E      at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:69)
                        E      at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:131)
                        E      at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:113)
                        E      at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:89)
                        E      at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:178)
                        E      at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:138)
                        E      at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:48)
                        E      at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:47)
                        .
                        .
                        .
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: getFragmentManager []
                        E      at com.facebook.stetho.common.ReflectionUtil.getMethod(ReflectionUtil.java:45)
                        E      at com.facebook.stetho.common.android.FragmentApi$ReflectionFragmentAccessor.<init>(FragmentApi.java:155)
                        E      at com.facebook.stetho.common.android.FragmentApi.<clinit>(FragmentApi.java:44)
                        E      ... 24 more
E  Caused by: java.lang.NoSuchMethodException: getFragmentManager []
                        E      at java.lang.Class.getConstructorOrMethod(Class.java:460)
                        E      at java.lang.Class.getMethod(Class.java:915)
                        E      at com.facebook.stetho.common.ReflectionUtil.getMethod(ReflectionUtil.java:43)
                        E      ... 26 more
```

Not entirely sure if the ```getFragmentManager``` API is available in the v4 support Fragment class on all platform levels. The documentation doesn't seem to mention anything about this.

Perhaps we could use ```com.facebook.stetho.common.ReflectionUtil.tryGetMethod()``` to fix this?

**Comment by jasta** [comment]
This might be happening as a result of proguard.  Are you using the shrink
feature for your debug builds?  If yes, you have to make sure to keep a
bunch of methods from the support lib.

Note that this is an unfortunate oversight that we consider a bug in
Stetho.  We'll be addressing this shortly.

Cc @rickbrew for some context.

**Comment by hungryTux** [comment]
That's probably what it is. We do have proguard enabled on our debug builds. I'll change the proguard configuration to include these methods for now.

**Comment by hzsweers** [comment]
@hungryTux did you find what you needed to add to your proguard config to fix this?
