### ISSUE TITLE
Crash when switching activities: prefs change

### ISSUE THREAD

**Issue by mttmllns** [facebook/stetho#151]
Getting the following trace when switching activities while using Stetho (only while actively inspecting).

```
04-09 17:42:20.042    1697-1697/com.test.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.adobe.dps.viewer, PID: 1697
    java.lang.RuntimeException: Prefs change detected for unknown key=ADMS_PauseDate
            at com.facebook.stetho.inspector.domstorage.DOMStoragePeerManager$DevToolsSharedPreferencesListener.onSharedPreferenceChanged(DOMStoragePeerManager.java:136)
            at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:476)
            at android.app.SharedPreferencesImpl$EditorImpl.access$600(SharedPreferencesImpl.java:302)
            at android.app.SharedPreferencesImpl$EditorImpl$3.run(SharedPreferencesImpl.java:484)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Relevant code: https://github.com/facebook/stetho/blob/master/stetho/src/main/java/com/facebook/stetho/inspector/domstorage/DOMStoragePeerManager.java#L145

The preference change is being triggered by a third-party analytics library we're using so I unfortunately don't know much about the code.  I have been able to deduce the following, though:

1. If I leave the app by tapping the home button I see the `ADMS_PauseDate` is created and stored.  No crash, Stetho continues to work, and I can see the preference in Local Storage in Chrome.
1. If I return to the app `ADMS_PauseDate` is removed from the prefs (reflected by Stetho).  Still no crash.
1. If I switch between activities in my app it crashes.

I'd guess that when switching activities the preference is created and then very quickly removed. Perhaps too quick for Stetho?

Whatever's happening I'd say a good solution would be to not throw the RuntimeException.  The reality is the preference never ended up in `mCopy` and isn't in `entries` so never had a chance to make it into the UI.  Maybe log a warning if you're concerned?

Thanks!

**Comment by jasta** [comment]
Agreed, I will dig in soon and see about both fixing this and softening the error.

**Comment by jasta** [comment]
It does look very possibly a race.  `onSharedPreferenceChanged` is guaranteed to run on the main thread, but the commit can occur on any thread.  By the time we're notified, another commit can have been applied, removing the value from the in memory state.  This was an unfortunate oversight on our part.

I can't see a way to stop the race from happening (they would need to give us the new value, not just the key), so given that I think the right fix is to just soften the runtime exception to a log statement to the effect of `"Detected rapid put/remove of <key>"`.
