### ISSUE TITLE
OutOfMemory in large okhttp multipart request

### ISSUE THREAD

**Issue by hegazy** [facebook/stetho#186]
The request is of a `multipart/form` type while uploading a big file.

This is the stacktrace
```
Out of memory on a 65119390-byte allocation.
        "OkHttp http://192.168.1.21/file/upload" prio=5 tid=14 RUNNABLE
        | group="main" sCount=0 dsCount=0 obj=0x43204300 self=0x789f9798
        | sysTid=24656 nice=0 sched=0/0 cgrp=apps handle=2024950480
        | state=R schedstat=( 637555121 95680921 453 ) utm=32 stm=31 core=1
        at java.lang.String.<init>(String.java:~255)
        at java.lang.String.<init>(String.java:393)
        at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.readBodyAsString(NetworkEventReporterImpl.java:120)
        at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.requestWillBeSent(NetworkEventReporterImpl.java:80)
        at com.facebook.stetho.okhttp.StethoInterceptor.intercept(StethoInterceptor.java:49)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:803)
        at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
        at com.squareup.okhttp.Call.getResponse(Call.java:272)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
        at com.squareup.okhttp.Call.access$100(Call.java:34)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

CLog    Could not reproduce POST body: java.lang.OutOfMemoryError
```

**Comment by hegazy** [comment]
This was just a warning. I thought it's something weird but I've just seen what you had done as discussed in issue #88 .
