### ISSUE TITLE
Stetho crashes when it is opened with Network as the default tab

### ISSUE THREAD

**Issue by mengdilin** [facebook/stetho#215]
Stetho crashes when it is opened with Network as the default tab.
To see the crash:
1) Open stetho, go to Network tab.
2) Close stetho, reopen stetho (the default tab should be network)

Here is the stack trace:
```
07-06 17:53:58.359  26101-26101/com.facebook.stetho.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.facebook.stetho.inspector.protocol.module.DOM.createShadowDOMUpdate(DOM.java:231)
            at com.facebook.stetho.inspector.protocol.module.DOM.updateTree(DOM.java:213)
            at com.facebook.stetho.inspector.protocol.module.DOM.access$2800(DOM.java:51)
            at com.facebook.stetho.inspector.protocol.module.DOM$ProviderListener.onPossiblyChanged(DOM.java:634)
            at com.facebook.stetho.inspector.elements.android.AndroidDOMProvider$1.run(AndroidDOMProvider.java:65)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rickbrew** [comment]
Looks like this code is running before `mShadowDOM` is initialized. woops!
