### ISSUE TITLE
Crash when using Retrofit+OkHttp interceptor: "retrofit.RetrofitError: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference"

### ISSUE THREAD

**Issue by orospakr** [facebook/stetho#223]
In my Kotlin app, using Retrofit, Rx, and the Stetho OkHttp interceptor, my requests start crashing if I attach Chrome.

It seems to be getting surprised by the `mConnection field`, an OkHttp Connection object reference, being null on the OkHttpInspectorResponse object.  My best guess is that it relates to my use of Rx.

```
                        E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                        E      at com.facebook.stetho.okhttp.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:228)
                        E      at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:144)
                        E      at com.facebook.stetho.okhttp.StethoInterceptor.intercept(StethoInterceptor.java:72)
                        E      at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:227)
                        E      at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
                        E      at com.squareup.okhttp.Call.execute(Call.java:81)
                        E      at retrofit.client.OkClient.execute(OkClient.java:53)
                        E      at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                        E      ... 9 more
```

I can share more details as required!

**Comment by jasta** [comment]
This is known to happen if you don't add the stetho interceptor as a
network interceptor (client.networkInterceptors() not .interceptors())

**Comment by mheras** [comment]
@jasta solution works perfect :) Thanks!!!
