### ISSUE TITLE
NullPointerException in OkHttpInspectorResponse.connectionId()

### ISSUE THREAD

**Issue by Turbo87** [facebook/stetho#267]
I'm getting the following crash once Chrome is connected to the app and the app tries to do an HTTP request:

````java
09-02 06:00:27.044  28152-28197/... E/AndroidRuntime﹕ FATAL EXCEPTION: OkHttp Dispatcher
    Process: ..., PID: 28152
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
            at com.facebook.stetho.okhttp.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:228)
            at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:144)
            at com.facebook.stetho.okhttp.StethoInterceptor.intercept(StethoInterceptor.java:72)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
            at com.squareup.okhttp.Call.access$100(Call.java:34)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
````

I'm using the following lines in my `build.gradle` file:

```gradle
    debugCompile 'com.facebook.stetho:stetho:1.1.1'
    compile 'com.facebook.stetho:stetho-okhttp:1.1.1'

    compile 'com.squareup.okhttp:okhttp:2.5.0'
```

**Comment by jasta** [comment]
It's possible you accidentally used `okHttpClient.interceptors().add(...)` instead of <tt>okHttp.<b>networkInterceptors()</b>.add(...)</tt>.  An NPE is probably the wrong response out of Stetho, but it can't work all the same because interceptors provide very different kinds of information than the network interceptors.

**Comment by Turbo87** [comment]
That is indeed possible. I was not aware that there was more than one kind of interceptors in OkHttp...

**Comment by BBlackwo** [comment]
@jasta I had the same issue. Thanks for clarifying!

**Comment by TWiStErRob** [comment]
@jasta As a safety measure, would it be possible to add a fail-fast null-check at `StethoInterceptor.intercept` or in `OkHttpInspectorResponse` constructor and throw a useful exception pointing this out?

**Comment by slezica** [comment]
I had the same problem, 2 years later, found this issue and solved it by using `addNetworkInterceptor`. It would be great if the `Exception` message suggested this.
