### ISSUE TITLE
Proguard prevents from building

### ISSUE THREAD

**Issue by fabiendem** [facebook/stetho#304]
Hi all,

When proguard is enabled, my Build is failing with the following message:
```
:app:proguardDevelopmentDebugMinified
Unexpected error while performing partial evaluation:
  Class       = [com/facebook/stetho/server/LocalSocketHttpServer]
  Method      = [listenOnAddress(Ljava/lang/String;)V]
  Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [com/facebook/stetho/server/LocalSocketHttpServer$WorkerThread] (with 3 known super classes) and [com/facebook/stetho/server/LocalSocketHttpServerConnection] (with 1 known super classes))
Exception while processing task 
java.lang.IllegalArgumentException: Can't find common super class of [com/facebook/stetho/server/LocalSocketHttpServer$WorkerThread] (with 3 known super classes) and [com/facebook/stetho/server/LocalSocketHttpServerConnection] (with 1 known super classes)
	at proguard.evaluation.value.TypedReferenceValue.findCommonClass(TypedReferenceValue.java:441)
	at proguard.evaluation.value.TypedReferenceValue.generalize(TypedReferenceValue.java:277)
	at proguard.evaluation.value.TypedReferenceValue.generalize(TypedReferenceValue.java:201)
	at proguard.evaluation.value.ReferenceValue.generalize(ReferenceValue.java:298)
	at proguard.evaluation.Variables.generalize(Variables.java:136)
	at proguard.evaluation.TracedVariables.generalize(TracedVariables.java:118)
	at proguard.optimize.evaluation.PartialEvaluator.generalizeVariables(PartialEvaluator.java:1257)
	at proguard.optimize.evaluation.PartialEvaluator.visitExceptionInfo(PartialEvaluator.java:1057)
	at proguard.classfile.visitor.ExceptionHandlerFilter.visitExceptionInfo(ExceptionHandlerFilter.java:67)
	at proguard.classfile.attribute.CodeAttribute.exceptionsAccept(CodeAttribute.java:186)
	at proguard.optimize.evaluation.PartialEvaluator.evaluateExceptionHandlers(PartialEvaluator.java:1019)
	at proguard.optimize.evaluation.PartialEvaluator.evaluateInstructionBlockAndExceptionHandlers(PartialEvaluator.java:574)
	at proguard.optimize.evaluation.PartialEvaluator.visitCodeAttribute0(PartialEvaluator.java:271)
	at proguard.optimize.evaluation.PartialEvaluator.visitCodeAttribute(PartialEvaluator.java:188)
	at proguard.optimize.evaluation.SimpleEnumUseChecker.visitCodeAttribute(SimpleEnumUseChecker.java:115)
	at proguard.classfile.attribute.CodeAttribute.accept(CodeAttribute.java:101)
	at proguard.classfile.ProgramMethod.attributesAccept(ProgramMethod.java:81)
	at proguard.classfile.attribute.visitor.AllAttributeVisitor.visitProgramMember(AllAttributeVisitor.java:95)
	at proguard.classfile.util.SimplifiedVisitor.visitProgramMethod(SimplifiedVisitor.java:92)
	at proguard.classfile.ProgramMethod.accept(ProgramMethod.java:73)
	at proguard.classfile.ProgramClass.methodsAccept(ProgramClass.java:516)
	at proguard.optimize.evaluation.SimpleEnumUseChecker.visitProgramClass(SimpleEnumUseChecker.java:102)
	at proguard.classfile.ProgramClass.accept(ProgramClass.java:358)
	at proguard.classfile.ClassPool.classesAccept(ClassPool.java:124)
	at proguard.optimize.Optimizer.execute(Optimizer.java:389)
	at proguard.ProGuard.optimize(ProGuard.java:328)
	at proguard.ProGuard.execute(ProGuard.java:127)
	at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
	at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:139)
	at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:115)
	at com.android.builder.tasks.Job.runTask(Job.java:48)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:227)
	at java.lang.Thread.run(Thread.java:745)
:app:dexDevelopmentDebugMinified
```

I use the proguard-android-optimize.txt version and I have the following proguard exception enabled:
```
# Stetho
-keep class com.facebook.stetho.** { *; }
-dontwarn com.facebook.stetho.**
```

Any idea?
Cheers!

**Comment by jasta** [comment]
This is likely to do with our continued use of the deprecated Apache HTTPClient library.  I am going to work on fixing that for the next release, which you can track at #288.  If you're sufficiently motivated, you could check out that branch, build, and retest with the new jar to make sure my assumption is correct.

**Comment by jasta** [comment]
Should be fixed.
