### ISSUE TITLE
Stetho 1.2.0 / NullPointerException for connection

### ISSUE THREAD

**Issue by johnjohndoe** [facebook/stetho#320]
I am trying to intercept OkHttp 2.7.0 with Stetho 1.2.0. This fails with a `NullPointerException` for the connection object:

```
E  java.lang.NullPointerException: Attempt to invoke virtual method 
            'int java.lang.Object.hashCode()' on a null object reference
E      at com.facebook.stetho.okhttp.StethoInterceptor$OkHttpInspectorResponse
            .connectionId(StethoInterceptor.java:228)
E      at com.facebook.stetho.inspector.network.NetworkEventReporterImpl
            .responseHeadersReceived(NetworkEventReporterImpl.java:144)
E      at com.facebook.stetho.okhttp.StethoInterceptor.intercept(StethoInterceptor.java:72)
E      at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
E      at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
E      at com.squareup.okhttp.Call.access$100(Call.java:35)
E      at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
E      at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E      at java.lang.Thread.run(Thread.java:818)
```

**Comment by jasta** [comment]
You are using `okhttp.interceptors().add(...)` instead of `okhttp.networkInterceptors().add(...)`.  We should do a better job of catching this and producing a more meaningful error TBH.

**Comment by johnjohndoe** [comment]
Thanks!
