### ISSUE TITLE
NPE in ShadowDocument$Update.getGarbageElements (V1.2.0)

### ISSUE THREAD

**Issue by tomtanti** [facebook/stetho#330]
Hi,

This NPE occurs sometimes during view paging and inspecting the app in Chrome.

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object com.facebook.stetho.inspector.elements.ElementInfo.parentElement' on a null object reference
       at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getGarbageElements(ShadowDocument.java:325)
       at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:345)
       at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:327)
       at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
       at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:647)
       at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by rickbrew** [comment]
Thanks! I think I have this one figured out

**Comment by tomtanti** [comment]
Cool. Thanks.
