### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by droidandrew** [facebook/stetho#381]
I'm can't reproduce it every time  (version 1.3.1)

```
Process: com.adoriasoft.quietping, PID: 9303
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null
at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:388)
at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:372)
at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:327)
at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:682)
at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5951)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by dabluck** [comment]
happening on 4.4 samsung tablet.

**Comment by jasta** [comment]
Hmm, this looks like it could be the case that we assume the old parent wasn't also removed causing getIdForObject to yield null (but we assume this can't be and use int).  The fix should be straight forward, something like:
```java
Integer parentNodeId = mObjectIdMpapper.getIdforObject(...);
Integer nodeId = ...;
if (nodeId != null && parentNodeId != null) {
  onChildNodeRemoved(...);
}
```

Can you repro this issue?  Would be interesting to see what the value of newElementInfo and oldElementInfo was to at least confirm that it's reasonable to see this case in practice.

**Comment by martinobrink** [comment]
I'm also seing this issue. Pretty consistently crashes on my end. crashes seen on various Android devices, various Android versions. 

Stetho versions:
com.facebook.stetho:stetho:1.3.1
com.facebook.stetho:stetho-okhttp3:1.3.1

stacktrace similar:

05-27 09:47:26.925 30189-30189/removed.debug D/AndroidRuntime: Shutting down VM
05-27 09:47:26.925 30189-30189/removed.debug W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4108e2a0)
05-27 09:47:27.005 30189-30189/removed.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              java.lang.NullPointerException
                                                                                  at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:388)
                                                                                  at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
                                                                                  at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:372)
                                                                                  at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:327)
                                                                                  at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
                                                                                  at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:682)
                                                                                  at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
                                                                                  at android.os.Handler.handleCallback(Handler.java:615)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:4867)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
                                                                                  at dalvik.system.NativeStart.main(Native Method)
05-27 09:47:32.350 30189-30189/removed.debug I/Process: Sending signal. PID: 30189 SIG: 9

**Comment by jasta** [comment]
Can you repro with the sample app?  Would be great if we had a repro case locally we could try out.

**Comment by hegazy** [comment]
It happens with me a lot during orientation change with inspecting on. I don't know how is this related to the issue itself. It's reproducible in an app I'm developing just like that, I can't share the code, but I think I can help.

**Comment by jasta** [comment]
Some print debugging might reveal something interesting about the state of things here.  Without a repro or extra logging I'm pretty stuck here.  I obviously coudl just throw in a null pointer check but the risk then is that the algorithm would yield an incorrect UI tree.  Not crashing is important, of course, but providing bad debugging info is also very important.  My preference would be to figure out why our algorithm is confused here and address that directly.

**Comment by Axolot1** [comment]
This happen when i set "setRetainInstance(true)" and rotate the screen.
my code:
if(mObservable == null) {
   mObservable = api.getUsers(ids).cache();
}
subscription = mObservable.subscribeOn(Schedulers.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(mObserver);
without setRetainInstance(true) it works just fine;

**Comment by itxuye** [comment]
I  got the same problem happening on 5.1 MI Phone .

**Comment by frannois** [comment]
happens to me while  cycling through a viewpager. I am still investigating the code. Could be related to recycling ?

**Comment by frannois** [comment]
@jasta i get the crash in Document.java line 388
I guess that we get the intvalue NPE because the `oldElementInfo` is not in the `mObjectIdMapper` and we can't put null in an `int`.
My knowledge of the code stops here. I could investigate a little bit more on why it is not part of the map but I feel like it is a racing condition.

**Comment by ggunders** [comment]
same error happens quite frequently. latest is during an activity finishing.

**Comment by andygoldfinch** [comment]
This error happens frequently when switching between fragments (some with nested fragments) in an activity, using the BottomNavigationBar from com.ashokvarma.bottomnavigation 

The error happens about once every 10 minutes of app debugging.

**Comment by rickbrew** [comment]
I'm unfortunately unable to reproduce this myself. I have an idea or two based on Axolot1's comment re: `setRetainInstance`, but without a repro I'm limited to archeological and forensic debugging, and won't be able to verify a fix.

Would someone be able to get me a minimal repro? A pull request for stetho-sample would be fantastic!

**Comment by rickbrew** [comment]
Okay so the good news is that a simple null check does, in fact, prevent the crash.

The bad news is there is another bug that immediately popped up.

The general problem here is that we have an element E1 with a child E2 and then it has a child E3. In non-abstract terms, E1->E2->E3 is really ViewGroup->Fragment->View, with the Fragment having `setRetainedInstance(true)`. 

In one `Document` update, we drop both E1 and E3 and replace them with E4 and E5. That means E2 is being reparented from E1 over to E3.

So we go from:

```
+ E1
|-+ E2
  |- E3
```

to:

```
+ E4
|-+ E2
  |- E5
```

E1 and E3 are destroyed and "garbage collected" (put in quotes because it's something Stetho is doing, not just the Java GC). 

The problem is that Chrome now shows this reality:

```
+ E4
|-+ E2
  |- E3
  |- E5
```

Woops, E3 is still attached because we never sent a childRemoved event to Chrome about E2. Chrome will have removed E2 because we told it to remove E1, but then we said to childInsert E2 underneath E4, and I guess it didn't realize that E3 was part of the bargain.

At least, that's my current theory. So, further investigation is needed to get the correct solution from here.

**Comment by rickbrew** [comment]
Also, I should be able to look at this some more next week, once I've wrapped up a few other obligations

**Comment by rickbrew** [comment]
Okay I accidentally pushed straight into master instead of creating a pull request. But hey, there's the fix :)

**Comment by andhie** [comment]
I am still facing this issue
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
  at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:388)
  at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
  at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:372)
  at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:327)
  at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
  at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:682)
  at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6119)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

An Activity (from an SDK i used) is set to `android:configChanges="orientation|screenSize"` but is not handled in Java via the `onConfigurationChanged()` method. Next i resized the Activity using Nougat Multi-Window feature, try resizing will cause the exception.

**Comment by rickbrew** [comment]
argh :( @andhie  can you make a new issue for that? is it possible for you to create a minimal repro inside of the stetho sample app that causes this to happen, and submit that as a PR?
