### ISSUE TITLE
ANR when periodically (1 minute) update text in a TextView

### ISSUE THREAD

**Issue by doritoswb** [facebook/stetho#384]
Hi, I applied stetho in my android app, and I found the app will be ANR sometimes, the following are the ANR trace info, seems it was caused by stetho, please help to investigate it.
Thanks.

BTW, why stetho will catch the "afterTextChanged" call, for constructing the UI frame in stetho's "Element" tab?

----- pid 30206 at 2016-05-17 18:33:10 -----
Cmd line: wg.roomis.media
ABI: arm
Build type: optimized
Zygote loaded classes=3405 post zygote classes=1731
Intern table: 37759 strong; 557 weak
JNI: CheckJNI is on; globals=744
Libraries: /system/lib/libandroid.so /system/lib/libaudioeffect_jni.so /system/lib/libboot_optimization.so /system/lib/libcompiler_rt.so /system/lib/libjavacrypto.so /system/lib/libjnigraphics.so /system/lib/libmedia_jni.so /system/lib/librs_jni.so /system/lib/libsoundpool.so /system/lib/libwebviewchromium_loader.so libjavacore.so (11)
Heap: 2% free, 9MB/9MB; 114755 objects
Dumping cumulative Gc timings
Total number of allocations 627884
Total bytes allocated 73MB
Free memory 215KB
Free memory until GC 215KB
Free memory until OOME 70MB
Total memory 9MB
Max memory 80MB
Total mutator paused time: 0
--more--
Total time waiting for GC to complete: 20.024ms

DALVIK THREADS (26):
"main" prio=5 tid=1 Sleeping
  | group="main" sCount=1 dsCount=0 obj=0x73e28700 self=0xb483d500
  | sysTid=30206 nice=0 cgrp=default sched=0/0 handle=0xb6fc3bec
  | state=S schedstat=( 9590249935 1802249218 13759 ) utm=827 stm=132 core=0 HZ=100
  | stack=0xbe493000-0xbe495000 stackSize=8MB
  | held mutexes=
  at java.lang.Thread.sleep!(Native method)
- sleeping on <0x38e4d266> (a java.lang.Object)
  at java.lang.Thread.sleep(Thread.java:1031)
- locked <0x38e4d266> (a java.lang.Object)
  at java.lang.Thread.sleep(Thread.java:985)
  at android.net.LocalSocketImpl$SocketOutputStream.flush(LocalSocketImpl.java:161)
  at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:86)
- locked <@addr=0x130a6de0> (a java.io.BufferedOutputStream)
  at com.facebook.stetho.websocket.WriteHandler.write(WriteHandler.java:29)
- locked <0x126cd9a7> (a com.facebook.stetho.websocket.WriteHandler)
  at com.facebook.stetho.websocket.WebSocketSession.doWrite(WebSocketSession.java:102)
  --more--
  at com.facebook.stetho.websocket.WebSocketSession.sendText(WebSocketSession.java:58)
  at com.facebook.stetho.inspector.jsonrpc.JsonRpcPeer.invokeMethod(JsonRpcPeer.java:65)
  at com.facebook.stetho.inspector.helper.ChromePeerManager.sendMessageToPeers(ChromePeerManager.java:131)
  at com.facebook.stetho.inspector.helper.ChromePeerManager.sendNotificationToPeers(ChromePeerManager.java:115)
  at com.facebook.stetho.inspector.protocol.module.DOM$DocumentUpdateListener.onAttributeModified(DOM.java:340)
  at com.facebook.stetho.inspector.elements.Document$UpdateListenerCollection.onAttributeModified(Document.java:604)
  at com.facebook.stetho.inspector.elements.Document$ProviderListener.onAttributeModified(Document.java:688)
  at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider.onAttributeModified(AndroidDocumentProvider.java:186)
  at com.facebook.stetho.inspector.elements.android.TextViewDescriptor$ElementContext.afterTextChanged(TextViewDescriptor.java:78)
  at android.widget.TextView.sendAfterTextChanged(TextView.java:7695)
  at android.widget.TextView.setText(TextView.java:4066)
  at android.widget.TextView.setText(TextView.java:3915)
  at android.widget.TextView.setText(TextView.java:3890)
  --more--
  at wg.roomis.media.play.MediaPlayerActivity.updateDateTime(MediaPlayerActivity.java:137)
  at wg.roomis.media.play.MediaPlayerActivity.access$000(MediaPlayerActivity.java:32)
  at wg.roomis.media.play.MediaPlayerActivity$TimeReceiver.onReceive(MediaPlayerActivity.java:143)
  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5258)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by jasta** [comment]
Whoops, we should have made this asynchronous.  The reason it hooks it is so that the elements tab will update when the text changes as we put that as a searchable part of the UI.

**Comment by doritoswb** [comment]
So can you help to double check if it has been made asynchronous? And which version include the fix? Then I can try to integrate it in my app and test again.
Thanks a lot.

BTW: The version I used is "1.3.1"

**Comment by jasta** [comment]
I meant that we should have but didn't make it asynchronous.  There's no plan to modify this part of the code soon, though I admit it is a problem.  PR welcome :)

One of the reasons this hasn't bit us much in the past is because the communication is expected to be over a local socket which has very high throughput and so writing on the main thread hasn't really shown up before.  That said, it's still unwise to write to a socket on the main thread, even if it's locally connected, and so the code should really include asynchronous dispatch options and this particular code path should be using them...

**Comment by kshdreams** [comment]
"main" prio=5 tid=1 Sleeping
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x76a16bb0 self=0x7359c14c00
  | sysTid=6102 nice=-10 cgrp=default sched=0/0 handle=0x73e089d560
  | state=S schedstat=( 99706165807 12549720897 95576 ) utm=6958 stm=3012 core=5 HZ=100
  | stack=0x7fe204d000-0x7fe204f000 stackSize=8MB
  | held mutexes=
  at java.lang.Thread.sleep(Native method)
  - sleeping on <0x0995842c> (a java.lang.Object)
  at java.lang.Thread.sleep(Thread.java:373)
  - locked <0x0995842c> (a java.lang.Object)
  at java.lang.Thread.sleep(Thread.java:314)
  at android.net.LocalSocketImpl$SocketOutputStream.flush(LocalSocketImpl.java:185)
  at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:141)
  - locked <0x08f6def5> (a java.io.BufferedOutputStream)
  at com.facebook.stetho.websocket.WriteHandler.write(WriteHandler.java:29)
  - locked <0x0f89c48a> (a com.facebook.stetho.websocket.WriteHandler)
  at com.facebook.stetho.websocket.WebSocketSession.doWrite(WebSocketSession.java:102)
  at com.facebook.stetho.websocket.WebSocketSession.sendText(WebSocketSession.java:58)
  at com.facebook.stetho.inspector.jsonrpc.JsonRpcPeer.invokeMethod(JsonRpcPeer.java:65)
  at com.facebook.stetho.inspector.helper.ChromePeerManager.sendMessageToPeers(ChromePeerManager.java:131)

**Comment by kshdreams** [comment]
I've got same ANR sometimes.
do you have plan to solve this problem?

my stetho version is 1.5.1
