### ISSUE TITLE
NullPointerException StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:229)

### ISSUE THREAD

**Issue by sibelius** [facebook/stetho#388]
```
Fatal Exception: java.lang.NullPointerException
       at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:229)
       at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:143)
       at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:73)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at app.di.modules.NetModule$1.intercept(NetModule.java:82)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
```

I'm using:
 - Dagger 2, 
 - Retrofit 2, 

 `com.facebook.stetho:stetho:1.3.1`,
 `compile 'com.facebook.stetho:stetho-okhttp3:1.3.1`

**Comment by jasta** [comment]
I believe this is happening because you're adding `StethoInterceptor` as an application interceptor and not as a network interceptor.  Check the API carefully in `OkHttpClient.Builder`.  Also, I'm interested in finding a way to detect this and produce a better error.  Would be great if you could toss up a patch to avoid a crash and print a warning instead.  Or, perhaps even better, produce a crash but with an error message that explains the mistake :)
