### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by rogerou** [facebook/stetho#394]
## FATAL EXCEPTION: StethoWorker-main-2
                                                              Process: ibuger.opencom, PID: 7321
                                                              java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/cli/GnuParser;
                                                                  at com.facebook.stetho.dumpapp.Dumper.<init>(Dumper.java:37)
                                                                  at com.facebook.stetho.Stetho$Initializer$RealSocketHandlerFactory.create(Stetho.java:409)
                                                                  at com.facebook.stetho.server.LazySocketHandler.getSocketHandler(LazySocketHandler.java:42)
                                                                  at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                                                                  at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.cli.GnuParser" on path: DexPathList[[zip file "/data/app/ibuger.opencom-2/base.apk"],nativeLibraryDirectories=[/data/app/ibuger.opencom-2/lib/arm, /data/app/ibuger.opencom-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

I download the jar and compile,when I run the applcation ,it crash.
I have tried compile stetho-1.3.1 but it will compile with error .
> Error:Execution failed for task ':app:transformClassesWithDexForXiaoNeiDebug'.
 com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_91\bin\java.exe'' finished with non-zero exit value 2

**Comment by rogerou** [comment]
the 65K limits cause this , I have fixed it now. :)
