### ISSUE TITLE
Stetho throws Fatal Exception

### ISSUE THREAD

**Issue by jawadhassan** [facebook/stetho#398]
Stetho is throwing following exception 

`FATAL EXCEPTION: StethoWorker-main-22
                                                   java.lang.NoClassDefFoundError: javax/annotation/Nonnull
                                                       at java.lang.reflect.Method.isAnnotationPresent(Native Method)
                                                       at java.lang.reflect.Method.isAnnotationPresent(Method.java:284)
                                                       at com.facebook.stetho.inspector.MethodDispatcher.isDevtoolsMethod(MethodDispatcher.java:136)
                                                       at com.facebook.stetho.inspector.MethodDispatcher.buildDispatchTable(MethodDispatcher.java:116)
                                                       at com.facebook.stetho.inspector.MethodDispatcher.findMethodDispatcher(MethodDispatcher.java:53)
                                                       at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60)
                                                       at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                                                       at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                                                       at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                                                       at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                                                       at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                                                       at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
                                                       at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                                                       at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
                                                       at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
                                                       at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
                                                       at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
                                                       at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
                                                       at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
                                                       at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
                                                       at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                                                       at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
                                                    Caused by: java.lang.ClassNotFoundException: javax.annotation.Nonnull
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                       at java.lang.reflect.Method.isAnnotationPresent(Native Method) 
                                                       at java.lang.reflect.Method.isAnnotationPresent(Method.java:284) 
                                                       at com.facebook.stetho.inspector.MethodDispatcher.isDevtoolsMethod(MethodDispatcher.java:136) 
                                                       at com.facebook.stetho.inspector.MethodDispatcher.buildDispatchTable(MethodDispatcher.java:116) 
                                                       at com.facebook.stetho.inspector.MethodDispatcher.findMethodDispatcher(MethodDispatcher.java:53) 
                                                       at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60) 
                                                       at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129) 
                                                       at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111) 
                                                       at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87) 
                                                       at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176) 
                                                       at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136) 
                                                       at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44) 
                                                       at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45) 
                                                       at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117) 
                                                       at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83) 
                                                       at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84) 
                                                       at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61) 
                                                       at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52) 
                                                       at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63) 
                                                       at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33) 
                                                       at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36) 
                                                       at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167) `

**Comment by jasta** [comment]
This looks like your proguard rules have not kept @Nonnull in the APK and for some reason isAnnotationPresent(SomeOtherAnnotation.class) is failing because of this.  I believe a simple work around would be to tell proguard to keep `javax.annotation.*`.  Can you confirm that indeed without proguard in play you don't see this error?
