### ISSUE TITLE
NoClassDefFoundError - GnuParser

### ISSUE THREAD

**Issue by ashughes** [facebook/stetho#419]
When building with

    debugCompile 'com.facebook.stetho:stetho:1.3.1@aar'

I get the following crash at runtime:

    FATAL EXCEPTION: StethoWorker-main-1
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/cli/GnuParser;
        at com.facebook.stetho.dumpapp.Dumper.<init>(Dumper.java:37)
        at com.facebook.stetho.Stetho$Initializer$RealSocketHandlerFactory.create(Stetho.java:409)
        at com.facebook.stetho.server.LazySocketHandler.getSocketHandler(LazySocketHandler.java:42)
        at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
        at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.cli.GnuParser" on path: DexPathList[[zip file "/data/app/com.test.dev-2/base.apk"],nativeLibraryDirectories=[/data/app/com.test.dev-2/lib/arm64, /data/app/com.test.dev-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.facebook.stetho.dumpapp.Dumper.<init>(Dumper.java:37) 
        at com.facebook.stetho.Stetho$Initializer$RealSocketHandlerFactory.create(Stetho.java:409) 
        at com.facebook.stetho.server.LazySocketHandler.getSocketHandler(LazySocketHandler.java:42) 
        at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36) 
        at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167) 
    	Suppressed: java.lang.ClassNotFoundException: org.apache.commons.cli.GnuParser
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 6 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

The `1.3.1` jar works correctly if I include the Proguard rules manually in my project. However, I want to use the AAR so I can get the Proguard rules included in the library.

**Comment by ashughes** [comment]
Just to be clear, the above crash occurs when I open `chrome://inspect` (or on app startup if it's already open).

**Comment by longinoa** [comment]
@ashughes you commented on #305 does this also fail when you target the aar version?

**Comment by ashughes** [comment]
@longinoa I only get the crash when targeting `1.3.1@aar`. The `1.3.1` jar works correctly (no crash), but does not include the Proguard rules.

**Comment by longinoa** [comment]
@ashughes can you try this
```
debucCompile ( 'com.facebook.stetho:stetho:1.3.1@aar') {
    transitive=true
}
```

It sounds like you arent getting the dependency of the aar http://stackoverflow.com/questions/22795455/transitive-dependencies-not-resolved-for-aar-library-using-gradle

**Comment by longinoa** [comment]
I just tested this in a sample app of my own and was able to duplicate it crashing (logcat didnt give me the no class def found though) making my change to add the `transitive = true` fixed the problem.

**Comment by ashughes** [comment]
@longinoa Thanks, that worked! It'd be good if this were documented on the README. It'd be even better if the default artifact was the AAR, so you don't have to worry about it. :)

**Comment by longinoa** [comment]
@ashughes  I am looking into this ... Im new to pom's and maven. All that  is required is a `<packaging>aar</packaging>` on the project inside the pom right?

**Comment by ashughes** [comment]
@longinoa Sorry, I'm actually not sure. That's what I would assume.

**Comment by longinoa** [comment]
Okay I got this working, it should be in the next release thats due out today or tomorrow. Ill likely try and swing back to this issue to ask if its properly working for you

**Comment by longinoa** [comment]
Hey @ashughes  Can you verify with stetho 1.4.0.

**Comment by ashughes** [comment]
@longinoa Yup, 1.4.0 appears to work without `transitive = true`. Thanks!

**Comment by zsavely** [comment]
Unfortunately, I started facing this very issue when targeting `1.5.0`.
