### ISSUE TITLE
unknown error (code 14): Could not open database

### ISSUE THREAD

**Issue by hk0i** [facebook/stetho#431]
I haven't been able to open the database on my app when attaching the inspector.
The Web SQL tab is showing my database in the list, but when I expand it, it is empty.

When I try to run a query on a table I know exists, or type anything for that matter the following message appears:

> unknown error (code 14): Could not open database

![Web SQL Error Message](https://cloud.githubusercontent.com/assets/755669/18419942/cd3d84cc-781b-11e6-8c07-76965bf2025c.png)

*Note that the disclosure triangle is __opened__*

When I look in logcat I see the following:

> 09-11 12:27:45.449 5735-10647 E/SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
09-11 12:27:45.449 5735-10647 E/SQLiteLog: (14) os_unix.c:32456: (2) open(/jmdict.db) - 
09-11 12:27:45.455 5735-10647 E/SQLiteDatabase: Failed to open database '/jmdict.db'.
                                                android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                    at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
                                                    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
                                                    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
                                                    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
                                                    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:671)
                                                    at com.facebook.stetho.inspector.database.DefaultDatabaseConnectionProvider.performOpen(DefaultDatabaseConnectionProvider.java:64)
                                                    at com.facebook.stetho.inspector.database.DefaultDatabaseConnectionProvider.openDatabase(DefaultDatabaseConnectionProvider.java:32)
                                                    at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.openDatabase(SqliteDatabaseDriver.java:211)
                                                    at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.executeSQL(SqliteDatabaseDriver.java:143)
                                                    at com.facebook.stetho.inspector.protocol.module.Database.executeSQL(Database.java:130)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
                                                    at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
                                                    at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                                                    at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                                                    at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                                                    at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                                                    at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                                                    at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
                                                    at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                                                    at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
                                                    at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
                                                    at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
                                                    at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
                                                    at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
                                                    at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
                                                    at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
                                                    at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                                                    at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)

The DB itself is accessible at runtime and works fine for opening and querying. I am currently trying Stetho in hopes of pin pointing some performance issues in my database, but I can't figure out what's wrong here.

It looks like Stetho is looking for the file in the wrong place maybe? But I don't know how Stetho is even finding it in the first place to fix that, or if I can.

The documentation for Stetho was pretty weak. From the looks of it, things should just *work*.

**Comment by tibbi** [comment]
its indeed broken since 1.4. Try using stetho 1.3.1 till it gets fixed.

**Comment by longinoa** [comment]
There was a change to this in 1.4.0, let me dig in a bit.

**Comment by hk0i** [comment]
Awesome. Works great on 1.3.1.

**Comment by longinoa** [comment]
@hk0i I found the issue, as soon as Travis completes ill merge and cut a new release to fix this. Sorry for the troubles!

**Comment by hk0i** [comment]
No worries, thanks for the responsiveness. It was driving me totally nuts. There was *one* other post about this online and it seemed like the guy changed the database path in *his* code to fix it, which didn't make any sense to me.

When the new release is ready will I be able to reference it straight from my gradle file or will I have to pull in a jar or some such?

**Comment by longinoa** [comment]
an update to gradle will suffice, this was just a long standing bug that a recent code change exposed

**Comment by hk0i** [comment]
Awesome, where can I find the new release version information to update my gradle file?

**Comment by longinoa** [comment]
@hk0i Just shipped a new release, updated information here: facebook.github.io/stetho/

**Comment by hk0i** [comment]
@longinoa Thanks! I just now got around to updating to 1.4.1 and it works great.
