### ISSUE TITLE
ObjectMapper throws NPE inside throwing IllegalArgumentException

### ISSUE THREAD

**Issue by sureshjoshi** [facebook/stetho#447]
Hey all, I'm making a plugin for Stetho (Stetho 1.4.1) but I'm getting an NPE from:

```
@ChromeDevtoolsMethod
@SuppressWarnings("unused")
public JsonRpcResult getDatabaseTableNames(JsonRpcPeer peer, JSONObject params) {
    Timber.e("getDatabaseTableNames");
    GetDatabaseTableNamesResponse response = new GetDatabaseTableNamesResponse();
    try {
    Timber.e(params.toString());
    GetDatabaseTableNamesRequest request = mObjectMapper.convertValue(params, GetDatabaseTableNamesRequest.class);
    Timber.e(request.toString());
```

Here is the stack trace:

```
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.json.ObjectMapper._convertFromJSONObject(ObjectMapper.java:114)
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.json.ObjectMapper.convertValue(ObjectMapper.java:78)
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.robotpajamas.android.stethocb.stetho.Database$override.getDatabaseTableNames(Database.java:52)
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.robotpajamas.android.stethocb.stetho.Database$override.access$dispatch(Database.java)
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.robotpajamas.android.stethocb.stetho.Database.getDatabaseTableNames(Database.java:0)
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
10-13 12:36:02.755 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
10-13 12:36:02.756 25194-25283/com.robotpajamas.android.stethocb W/System.err:     at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
```

At the end of the day, I seem to be doing something wrong, just noting that it's an exception inside an exception.

**Comment by sureshjoshi** [comment]
Arg... Caused by InstantRun

`public static transient volatile com.android.tools.fd.runtime.IncrementalChange com.robotpajamas.android.stethocb.stetho.Database$GetDatabaseTableNamesRequest.$change`

Fixed by disabling instant run, but that's not ideal... I think it'll be fine when I turn it into a library, but for now - I can't run with instant run on.

**Comment by sureshjoshi** [comment]
Oh, and for context, here is the plugin. It's for viewing Couchbase.

https://github.com/RobotPajamas/Stetho-Couchbase

**Comment by longinoa** [comment]
hmmm I havent played with instant run enough to know how they modify class loaders. do you know of a workaround other than disabling it?

**Comment by sureshjoshi** [comment]
@longinoa No, I don't. If you're pulling in a library, it doesn't affect you, as Gradle libs aren't compiled in instant-run formats - but it's a giant pain when trying to develop a plugin  :)

**Comment by longinoa** [comment]
Im gonna close this out for now then as I dont see any work items.

Thanks for making a plugin! let us know if you find any other issues

**Comment by sureshjoshi** [comment]
@longinoa You don't think it's worth handling Instant Run for development? Instant run is how everything is going nowadays. 

I've got a few more plugins to work on, so maybe I'll see something in there - I would have assumed Jackson or similar might have dealt with this?

**Comment by longinoa** [comment]
Sorry - this isn't related to instant run - not sure why it passes if you dont use it.

Looking at this a bit more in depth we shouldn't be throwing a NPE here, and this is likely masking a different bug. the return of `getValueForField` can be null if `setValue` results in an `IllegalArgumentException` we call `getClass` on `setValue` this is the NPE. 

I can fix this easily then you will hopefully have enough information to turn instant run back on as it shouldnt be affecting this. 

The only delta is if you are doing something in the initialization that caches.

**Comment by sureshjoshi** [comment]
Yeah, I guess I was focused on the Instant Run workaround. The original problem is the possibility of a NPE getting thrown inside a catch block, if a field was null. 

The extra instant run fields seem to have caused a situation where an NPE existed in the catch block, but not sure if there was another way to cause it.
