### ISSUE TITLE
SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by Aexyn** [facebook/stetho#475]
I am using different for [debug mode](https://www.littlerobots.nl/blog/stetho-for-android-debug-builds-only/) Stetho. To fetch databases, I use this:

```
final Stetho.DefaultInspectorModulesBuilder builder = new Stetho.DefaultInspectorModulesBuilder(this);
		final List<File> databaseFiles = new ArrayList<>();
		DatabaseFilesProvider filesProvider = new DatabaseFilesProvider() {
			@Override
			public List<File> getDatabaseFiles() {
				if(databaseFiles.size()>0){
					return databaseFiles;
				}
				for (String filename : DebugApplication.this.databaseList()) {
					databaseFiles.add(new File(filename));
				}
				FilenameFilter filenameFilter = new FilenameFilter() {
					@Override
					public boolean accept(File dir, String filename) {
						return filename.endsWith(".sql")
								|| filename.endsWith(".sqlite")
								|| filename.endsWith(".db");
					}
				};
				//Add External Databases if Present
				if (isExternalAvailable()) {
					File absoluteFile = null;
					try {
						absoluteFile = DebugApplication.this.getExternalFilesDir(null).getAbsoluteFile();
					} catch (Exception e) {
						e.printStackTrace();
					}
					if (absoluteFile != null) {
						String[] externalDatabases = absoluteFile.list(filenameFilter);
						for (String db : externalDatabases) {
							databaseFiles.add(new File(absoluteFile, db));
						}
					}
				}
				return databaseFiles;
			}
		};

//        filesProvider.getDatabaseFiles();
		builder.databaseFiles(filesProvider);
		final Iterable<ChromeDevtoolsDomain> domains = builder.finish();
		InspectorModulesProvider modulesProvider = new InspectorModulesProvider() {
			@Override
			public Iterable<ChromeDevtoolsDomain> get() {
//              Iterable<ChromeDevtoolsDomain> modules = Stetho.defaultInspectorModulesProvider(DebugApplication.this).get();
				return domains;
			}
		};

		Stetho.Initializer initializer = Stetho.newInitializerBuilder(this)
		                                       .enableWebKitInspector(modulesProvider)
		                                       .build();
		Stetho.initialize(initializer);
```

I have basically 4 databases in my app: 2 on Internal storage (which comes through DebugApplication.this.databaseList()) and 2 on External storage (via DebugApplication.this.getExternalFilesDir(null).getAbsoluteFile()) .

When on Stetho **1.3.1** , **Internal**  dbs works fine but external gives this error:
```
E/SQLiteLog: (14) cannot open file at line 31307 of [2ef4f3a5b1]
E/SQLiteLog: (14) os_unix.c:31307: (2) open(/data/user/0/com.agnity.aconyx.mc/databases/mc_avtar_storage.db) - 
E/SQLiteDatabase: Failed to open database '/data/user/0/com.agnity.aconyx.mc/databases/mc_avtar_storage.db'.
                  android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                      at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
                      at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
                      at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.openDatabase(SqliteDatabaseDriver.java:207)
                      at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.getTableNames(SqliteDatabaseDriver.java:114)
                      at com.facebook.stetho.inspector.protocol.module.Database.getDatabaseTableNames(Database.java:108)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
                      at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
                      at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                      at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                      at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                      at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                      at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                      at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
                      at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                      at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
                      at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
                      at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
                      at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
                      at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
                      at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
                      at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
                      at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                      at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
W/System.err: com.facebook.stetho.inspector.jsonrpc.JsonRpcException: INVALID_REQUEST: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
W/System.err:     at com.facebook.stetho.inspector.protocol.module.Database.getDatabaseTableNames(Database.java:114)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
W/System.err:     at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
W/System.err:     at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
W/System.err:     at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
W/System.err:     at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
W/System.err:     at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
W/System.err:     at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
W/System.err:     at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
W/System.err:     at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
W/System.err:     at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
W/System.err:     at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
W/System.err:     at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
W/System.err:     at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
W/System.err:     at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
W/System.err:     at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
W/ChromeDevtoolsServer: Error processing remote message
```
And when on **1.4.2**, **external** works fine and internal gives this error.:
```
D/ChromeDevtoolsServer: Method not implemented: Not implemented: ApplicationCache.enable
D/ChromeDevtoolsServer: Method not implemented: Not implemented: ApplicationCache.getFramesWithManifests
D/ChromeDevtoolsServer: Method not implemented: Not implemented: HeapProfiler.enable
E/SQLiteLog: (14) cannot open file at line 31307 of [2ef4f3a5b1]
E/SQLiteLog: (14) os_unix.c:31307: (2) open(/configuration_storage) - 
E/SQLiteDatabase: Failed to open database '/configuration_storage'.
                  android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                      at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
                      at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
                      at com.facebook.stetho.inspector.database.DefaultDatabaseConnectionProvider.performOpen(DefaultDatabaseConnectionProvider.java:64)
                      at com.facebook.stetho.inspector.database.DefaultDatabaseConnectionProvider.openDatabase(DefaultDatabaseConnectionProvider.java:32)
                      at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.openDatabase(SqliteDatabaseDriver.java:211)
                      at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.getTableNames(SqliteDatabaseDriver.java:121)
                      at com.facebook.stetho.inspector.protocol.module.Database.getDatabaseTableNames(Database.java:108)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
                      at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
                      at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                      at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                      at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                      at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                      at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                      at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
                      at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                      at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
                      at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
                      at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
                      at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
                      at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
                      at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
                      at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
                      at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                      at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
W/System.err: com.facebook.stetho.inspector.jsonrpc.JsonRpcException: INVALID_REQUEST: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
W/System.err:     at com.facebook.stetho.inspector.protocol.module.Database.getDatabaseTableNames(Database.java:114)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
W/System.err:     at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
W/System.err:     at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
W/System.err:     at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
W/System.err:     at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
W/System.err:     at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
W/System.err:     at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
W/System.err:     at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
W/System.err:     at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
W/System.err:     at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
W/System.err:     at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
W/System.err:     at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
W/System.err:     at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
W/System.err:     at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
W/System.err:     at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
W/System.err:     at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
W/ChromeDevtoolsServer: Error processing remote message
```

It Shows all database list in WebSQL list.. but just unable to open. I don't know what to do to get both working.. may be change my code.. Pls help

**Comment by longinoa** [comment]
In your `1.4.2` version your exception: 
```
E/SQLiteDatabase: Failed to open database '/configuration_storage'
```
looks like your provider is not providing a fully qualified File path - that is likely your problem

**Comment by Aexyn** [comment]
But why it worked on `1.3.2` ?

**Comment by jasta** [comment]
@Aexyn without going back too deep in the history there were bugs in this area that we have been addressing (even more changes coming in the next release) and so I suspect that's why things changed to 1.4.2.  As for @longinoa's comment I can confirm your code isn't using fully qualified paths (`databaseList` uses only string names) and it likely broke as a result of fixes (ironically) in stetho itself that better delegates to your database files provider for the final authority.

To fix this issue though you should reach for a composition strategy to use our code to resolve the internal databases as we would do normally, but extend it as such:

```java
  class ExternalDatabaseFilesProvider implements DatabaseFilesProvider {
    // provide external only files...
  }

  class CompositeDatabaseFilesProvider implements DatabaseFilesProvider {
    CompositeDatabaseFIlesProvider(List<DatabaseFilesProvider> providers) { ... }

    getDatabaseFiles() {
      files = new HashSet<>();
      for (provider : providers) {
        files.addAll(provider.getDatabaseFiles());
      }
      return Arrays.asList(files.toArray(new File[files.size()])));
    }
  }

  .databaseFiles(
      new CompositeDatabaseFilesProvider(
          new DefaultDatabaseFilesProvider(context),
          new ExternalDatabaseFIlesProvider(context)));
```

**Comment by Aexyn** [comment]
Yeah.. the things do change in 1.4.2. Till 1.3.1 , Stetho might be adding the searching at default database location of app ( in my case /data/user/0/<app-name>/databases/configuration_storage). and now I have to provide the full path.

the change I have to do is to change this:
```
for (String filename : DebugApplication.this.databaseList()) {
	databaseFiles.add(new File(filename));
}

```
to:
```
for (String filename : DebugApplication.this.databaseList()) {
	databaseFiles.add(getDatabasePath(filename));
}
```

and now everything is working fine.
Thanks :)
