### ISSUE TITLE
Stetho crashes if opened with Chrome://inspect already open, or when I open it.

### ISSUE THREAD

**Issue by shehabix** [facebook/stetho#501]
App crashes once I start the inspection in Chrome

in Gradle:
```
    defaultConfig {
        .
        .
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }


dependencies {
    compile project(':jiraapi')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.conceal:conceal:1.1.3@aar'
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:design:25.2.0'
    compile 'com.android.support:support-vector-drawable:25.2.0'

    compile 'com.google.zxing:core:3.3.0'
    compile 'com.google.zxing:android-integration:3.3.0'
    compile 'com.google.zxing:android-core:3.3.0'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.0.1'
    compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.4.1'
    compile 'com.google.dagger:dagger:2.3'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.android.support:multidex:1.0.1'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.3'

    debugCompile 'com.facebook.stetho:stetho:1.3.1@aar'

    testCompile 'junit:junit:4.12'
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    androidTestCompile('com.android.support:multidex-instrumentation:1.0.1') {
        exclude group: 'com.android.support', module: 'multidex'
    }

```

**Stack Trance:**

```
Process: ***, PID: 13690
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/newrelic/agent/android/instrumentation/JSONArrayInstrumentation;
 at com.facebook.stetho.inspector.ChromeDiscoveryHandler.handlePageList(ChromeDiscoveryHandler.java:133)
 at com.facebook.stetho.inspector.ChromeDiscoveryHandler.handleRequest(ChromeDiscoveryHandler.java:81)
 at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
 at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
 at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
 at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
 at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
 at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
 at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.newrelic.agent.android.instrumentation.JSONArrayInstrumentation" on path: DexPathList[[zip file "/data/app/****.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/****.dev-1/lib/arm64, /data/app/****-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 at com.facebook.stetho.inspector.ChromeDiscoveryHandler.handlePageList(ChromeDiscoveryHandler.java:133) 
 at com.facebook.stetho.inspector.ChromeDiscoveryHandler.handleRequest(ChromeDiscoveryHandler.java:81) 
 at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84) 
 at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61) 
 at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52) 
 at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63) 
 at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33) 
 at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36) 
 at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167) 
Suppressed: java.lang.ClassNotFoundException: com.newrelic.agent.android.instrumentation.JSONArrayInstrumentation
 at java.lang.Class.classForName(Native Method)
 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 		... 10 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
02-26 03:59:57.592 13690-13740/? E/AndroidRuntime: FATAL EXCEPTION: StethoWorker-main-1
Process: ****.dev, PID: 13690
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/newrelic/agent/android/instrumentation/JSONObjectInstrumentation;
 at com.facebook.stetho.inspector.ChromeDiscoveryHandler.handleVersion(ChromeDiscoveryHandler.java:106)
 at com.facebook.stetho.inspector.ChromeDiscoveryHandler.handleRequest(ChromeDiscoveryHandler.java:79)
 at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
 at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
 at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
 at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
 at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
 at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
 at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.newrelic.agent.android.instrumentation.JSONObjectInstrumentation" on path: DexPathList[[zip file "/data/app/****.dev-1/base.apk"],nativeLibraryDirectories=[/data/app/****.dev-1/lib/arm64, /data/app/****.dev-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 at com.facebook.stetho.inspector.ChromeDiscoveryHandler.handleVersion(ChromeDiscoveryHandler.java:106) 
 at com.facebook.stetho.inspector.ChromeDiscoveryHandler.handleRequest(ChromeDiscoveryHandler.java:79) 
 at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84) 
 at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61) 
 at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52) 
 at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63) 
 at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33) 
 at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36) 
 at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167) 
Suppressed: java.lang.ClassNotFoundException: com.newrelic.agent.android.instrumentation.JSONObjectInstrumentation
 at java.lang.Class.classForName(Native Method)
 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
 		... 10 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by shehabix** [comment]
This issue was with Android Studio 2.3 RC1 and the Gradle Plugin associated with it :(
