### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by flztsj** [facebook/stetho#523]
04-06 11:51:44.724 6739-8108/com.transsion.magicshow E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                       Process: com.transsion.magicshow, PID: 6739
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                                           at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:229)
                                                                           at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:143)
                                                                           at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:73)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                           at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
                                                                           at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:761)

**Comment by flztsj** [comment]
check you code

new OkHttpClient.Builder()
    .addNetworkInterceptor(new StethoInterceptor())
    .build()
