### ISSUE TITLE
App crashes when Stetho is open during a screen rotation

### ISSUE THREAD

**Issue by paour** [facebook/stetho#534]
Stacktrace:

```
java.lang.IllegalStateException: Fragment has not been attached yet.
    at android.support.v4.app.Fragment.instantiateChildFragmentManager(Fragment.java:2154)
    at android.support.v4.app.Fragment.getChildFragmentManager(Fragment.java:704)
    at com.facebook.stetho.common.android.FragmentCompatSupportLib$FragmentAccessorSupportLib.getChildFragmentManager(FragmentCompatSupportLib.java:101)
    at com.facebook.stetho.common.android.FragmentCompatSupportLib$FragmentAccessorSupportLib.getChildFragmentManager(FragmentCompatSupportLib.java:68)
    at com.facebook.stetho.common.android.FragmentCompatUtil.findFragmentForViewInFragment(FragmentCompatUtil.java:120)
    at com.facebook.stetho.common.android.FragmentCompatUtil.findFragmentForViewInFragmentManager(FragmentCompatUtil.java:99)
    at com.facebook.stetho.common.android.FragmentCompatUtil.findFragmentForViewInActivity(FragmentCompatUtil.java:83)
    at com.facebook.stetho.common.android.FragmentCompatUtil.findFragmentForViewInActivity(FragmentCompatUtil.java:56)
    at com.facebook.stetho.common.android.FragmentCompatUtil.findFragmentForView(FragmentCompatUtil.java:46)
    at com.facebook.stetho.inspector.elements.android.ViewGroupDescriptor.getElementForView(ViewGroupDescriptor.java:76)
    at com.facebook.stetho.inspector.elements.android.ViewGroupDescriptor.onGetChildren(ViewGroupDescriptor.java:47)
    at com.facebook.stetho.inspector.elements.android.ViewGroupDescriptor.onGetChildren(ViewGroupDescriptor.java:27)
    at com.facebook.stetho.inspector.elements.AbstractChainedDescriptor.getChildren(AbstractChainedDescriptor.java:118)
    at com.facebook.stetho.inspector.elements.Document.createShadowDocumentUpdate(Document.java:307)
    at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:341)
    at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:31)
    at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:720)
    at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:71)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)

                                                                           at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by paour** [comment]
Unfortunately, after a rotation, Chrome Web Tools won't connect, either.

```
D/ChromeDevtoolsServer: onOpen
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.canEmulate
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Console.setTracingBasedTimeline
I/ResponseBodyFileManager: Cleaned up temporary network files.
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Debugger.setAsyncCallStackDepth
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Debugger.skipStackFrames
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Runtime.enable
W/stetho: I/O error: java.io.IOException: Broken pipe
```

**Comment by maks** [comment]
I don't see this when running on the SDK emulator (x86_64 avd with 7.1.1) so perhaps this is a Genymotion specific issue?

**Comment by chalup** [comment]
I have the same issue on regular emulator.

**Comment by jasta** [comment]
@rickbrew any idea what's going on here?

**Comment by Placeable** [comment]
use isAdded() from fragment before calling getChildFragmentManager
