### ISSUE TITLE
Stetho with OkHttp 3.8.

### ISSUE THREAD

**Issue by naturalwarren** [facebook/stetho#541]
`Interceptor.Chain.connection()` was [marked nullable](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Interceptor.java#L38) in OkHttp 3.8.0. 

In `StethoInterceptor` we retrieve a connection and don't check for `null`. This causes Stetho to crash when calling [`OkHttpInspectorResponse.connectionId()`](https://github.com/facebook/stetho/blob/master/stetho-okhttp3/src/main/java/com/facebook/stetho/okhttp3/StethoInterceptor.java#L226) when a connection is not present. Stacktrace below:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
    at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:226)
    at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:145)
    at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:70)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:101)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:76)
```

Would you be interested in a PR that null checks `connection` and returns 0 for `connectionId` if a connection is not present? 

This is the only issue I've countered with Stetho 1.5 & OkHttp 3.8 thus far.

**Comment by naturalwarren** [comment]
@jasta Could you please take a peak at this?

**Comment by naturalwarren** [comment]
@rickbrew Trying for Rick :)

**Comment by naturalwarren** [comment]
Fixed in #544.

**Comment by Hazer** [comment]
@naturalwarren When this will be in a maven release?

**Comment by naturalwarren** [comment]
When the maintainers decide to cut a release. @jasta or @rickbrew may know.
