### ISSUE TITLE
NPE when use StethoInterceptor

### ISSUE THREAD

**Issue by Sabrak** [facebook/stetho#555]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                       at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:226)
                                                       at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:145)
                                                       at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:70)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by naturalwarren** [comment]
Looks like you're registered as a vanilla interceptor and not a network interceptor. See #549.

**Comment by Sabrak** [comment]
@naturalwarren Ooops, you are right. Thanks.
