### ISSUE TITLE
Use stetho-1.5.0-fatjar.jar in my project，throw NoSuchFieldError

### ISSUE THREAD

**Issue by liguobing** [facebook/stetho#566]
Error Log：
`java.lang.NoSuchFieldError: No static field abc_seekbar_tick_mark_material of type I in class Landroid/support/v7/appcompat/R$drawable; or its superclasses (declaration of 'android.support.v7.appcompat.R$drawable' appears in /data/app/com.li_xyz.lifekeeper-2/split_lib_dependencies_apk.apk:classes29.dex)
                                                                           at android.support.v7.widget.AppCompatDrawableManager.<clinit>(AppCompatDrawableManager.java:120)
                                                                           at android.support.v7.widget.AppCompatDrawableManager.get(AppCompatDrawableManager.java:84)
                                                                           at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                                           at android.support.design.widget.TabLayout$TabView.<init>(TabLayout.java:1517)
                                                                           at android.support.design.widget.TabLayout.createTabView(TabLayout.java:931)
                                                                           at android.support.design.widget.TabLayout.newTab(TabLayout.java:568)
                                                                           at android.support.design.widget.TabLayout.populateFromPagerAdapter(TabLayout.java:909)
                                                                           at android.support.design.widget.TabLayout.setPagerAdapter(TabLayout.java:900)
                                                                           at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:813)
                                                                           at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:774)
                                                                           at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:752)
                                                                           at com.li_xyz.lifekeeper.View.Activity.MainActivity.onCreate(MainActivity.java:63)
                                                                           at android.app.Activity.performCreate(Activity.java:6251)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Help me!What should I do?

**Comment by liguobing** [comment]
new discovery!
stetho and android.support.design.widget.* conflict
i use `android.support.design.widget.BottomNavigationView`、`android.support.design.widget.TabLayout` with stetho ,throw NoSuchFieldError!!!!!!!!!!

**Comment by jasta** [comment]
Oops.  The fatjar accidentally is including android/support/v4 and v7 R.class files so if you were to try to use a different version than the one we compiled against you'd run into this issue.

**Comment by gaj-programmer** [comment]
Is this issue of Fixed in v1.5.1 ? can i use 1.5.1 version now.
