### ISSUE TITLE
Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by yangheng362** [facebook/stetho#615]
Stetho will makes app crash at sometime.This is the crash log.
```
Fatal Exception: java.lang.IllegalStateException: Software rendering doesn't support hardware bitmaps
       at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:532)
       at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
       at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:120)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1434)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
       at android.widget.ImageView.onDraw(ImageView.java:1367)
       at android.view.View.draw(View.java:19192)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
       at android.view.View.draw(View.java:19062)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19060)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19195)
       at com.android.internal.policy.DecorView.draw(DecorView.java:788)
       at com.facebook.stetho.inspector.screencast.ScreencastDispatcher$BitmapFetchRunnable.updateScreenBitmap(ScreencastDispatcher.java:104)
       at com.facebook.stetho.inspector.screencast.ScreencastDispatcher$BitmapFetchRunnable.run(ScreencastDispatcher.java:74)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by coutliuxing** [comment]
me to !!! Android O

**Comment by ar-g** [comment]
same on Motorolla

**Comment by jhwsx** [comment]
Can this be solved?

**Comment by AntimKhel** [comment]
Hi, Is there any resolution for this issue?
