### ISSUE TITLE
java.lang.OutOfMemoryError: Could not allocate JNI Env

### ISSUE THREAD

**Issue by codingBobo** [facebook/stetho#627]
java.lang.OutOfMemoryError: Could not allocate JNI Env
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:729)
        at com.facebook.stetho.server.LocalSocketServer.listenOnAddress(LocalSocketServer.java:94)
        at com.facebook.stetho.server.LocalSocketServer.run(LocalSocketServer.java:74)
        at com.facebook.stetho.server.ServerManager$1.run(ServerManager.java:40)

I got this error on version 1.5.0，it looks like too many threads had be created。

**Comment by jasta** [comment]
Err, I think this may be something related to your application itself.  Stetho is only creating one thread to do this socket listening.
