### ISSUE TITLE
Stetho throwing exceptions that are inside a try/catch block

### ISSUE THREAD

**Issue by cesaramq** [facebook/stetho#664]
Hi, I'm facing this issue only when Stetho is open, I have a code where I replace some placeholders in a String. If the placeholders are not found, then I catch the exception and return the original String.

However, when Stetho is open it seems like the try/catch block was ignored by Stetho and it is still making my app to crash by throwing the exception that is supposed to be caught.

Here's the code (I'm using Square Phrase library):
`/**
     * This method resolves the {application_label} placeholder if any and returns the
     * original string with the application label value applied.
     * @param original - The string which will get its placeholders resolved.
     * @return The original string with the placeholders resolved, if any.
     */
    fun resolveApplicationLabel(original: String): String {
        val applicationLabel = resources.getString(R.string.application_label)
        return try {
            Phrase.from(original)
                    .put(APPLICATION_LABEL_NAME, applicationLabel)
                    .format().toString()
        } catch (e: IllegalArgumentException) {
            log.e(TAG, "No valid placeholders found in $original", e)
            original
        }
    }`

Version of Stetho: 1.5.1

**Comment by cesaramq** [comment]
I saw this on the logs, don't know if it helps:

```
2019-08-19 09:54:53.406 13816-13816/com.synchronoss.pcloud.android.syncdrive E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.synchronoss.pcloud.android.syncdrive, PID: 13816
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:388)
        at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
        at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:372)
        at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:327)
        at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
        at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:682)
        at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-08-19 09:54:53.424 696-696/? E/lowmemorykiller: Error writing /proc/13816/oom_score_adj; errno=22
```

i'm making this changes to a TextView when the Activity is getting created. So I'm not sure if this change of something in the layout while getting initialized could affect Stetho?

**Comment by cesaramq** [comment]
I saw this on the logs, don't know if it helps:

```
2019-08-19 09:54:53.406 13816-13816/com.test.myapp.android.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.myapp.android.myapp, PID: 13816
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.facebook.stetho.inspector.elements.Document$4.store(Document.java:388)
        at com.facebook.stetho.inspector.elements.ShadowDocument$Update.getChangedElements(ShadowDocument.java:297)
        at com.facebook.stetho.inspector.elements.Document.applyDocumentUpdate(Document.java:372)
        at com.facebook.stetho.inspector.elements.Document.updateTree(Document.java:327)
        at com.facebook.stetho.inspector.elements.Document.access$1200(Document.java:30)
        at com.facebook.stetho.inspector.elements.Document$ProviderListener.onPossiblyChanged(Document.java:682)
        at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider$1.run(AndroidDocumentProvider.java:67)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-08-19 09:54:53.424 696-696/? E/lowmemorykiller: Error writing /proc/13816/oom_score_adj; errno=22
```

i'm making this changes to a TextView when the Activity is getting created. So I'm not sure if this change of something in the layout while getting initialized could affect Stetho?

**Comment by cesaramq** [comment]
I found that it's not throwing the exceptions caught by a try/catch block, that was just something that happened as a consequence of Stetho's crash but it's not directly related.

This issue is basically the same as this other one: https://github.com/facebook/stetho/issues/381 which doesn't seem to be fully fixed unfortunately.
