### ISSUE TITLE
SyncAdapter on seperate thread causes Address already in use

### ISSUE THREAD

**Issue by remcomokveld** [facebook/stetho#87]
I initialized Stetho using the following code in my applications onCreate:

``` Java
Stetho.initialize(Stetho.newInitializerBuilder(this)
                .enableWebKitInspector(Stetho.defaultInspectorModulesProvider(this))
                .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                .build());
```

and then having the syncservice for a SyncAdapter running in a seperate thread by declaring the service in my AndroidManifest.xml

``` Xml
<service android:name=".service.SyncService"
  android:exported="true"
  android:process=":sync">
  
  <intent-filter>
    <action android:name="android.content.SyncAdapter"/>
  </intent-filter>
  <meta-data android:name="android.content.SyncAdapter"
      android:resource="@xml/syncadapter" />
</service>
```

causes the following exception

```
W/System.err﹕ java.io.IOException: Address already in use
W/System.err﹕ at android.net.LocalSocketImpl.bindLocal(Native Method)
W/System.err﹕ at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:309)
W/System.err﹕ at android.net.LocalServerSocket.<init>(LocalServerSocket.java:52)
W/System.err﹕ at com.facebook.stetho.server.LocalSocketHttpServer.bindToSocket(LocalSocketHttpServer.java:278)
W/System.err﹕ at com.facebook.stetho.server.LocalSocketHttpServer.listenOnAddress(LocalSocketHttpServer.java:138)
W/System.err﹕ at com.facebook.stetho.server.LocalSocketHttpServer.run(LocalSocketHttpServer.java:134)
W/System.err﹕ at com.facebook.stetho.Stetho$1.run(Stetho.java:80)
```

**Comment by jasta** [comment]
The address already in use bug was fixed in 1.0.1 and represents a simple logic bug that always prints this error even on success (whoops).

If this is the only symptom, you can safely ignore the error or upgrade to 1.0.1 and everything should be fine.
