### ISSUE TITLE
Out of memory when doing a lot of request

### ISSUE THREAD

**Issue by fourlastor** [facebook/stetho#88]
Hello, I was trying to inspect my network request while downloading a huge (150+) set of images for a grid in the app I work for. After scrolling fast enough Stetho threw an OOM.

I'm using Picasso to download the image and intercepting the network requests with StethoInterceptor:

```java
// standard Dagger module
    @Provides @Singleton OkHttpClient provideOkHttpClient() {
        return new OkHttpClient();
    }

    @Provides @Singleton Picasso providePicasso(@ForApplication Context context, OkHttpClient client) {
        return new Picasso.Builder(context).downloader(new OkHttpDownloader(client)).build();
    }


// overridden module for debug

    @Module(overrides = true, addsTo = AndroidModule.class, injects = PauseDebugApplication.class)
    static class DebugModule {
        @Provides @Singleton OkHttpClient provideDebugClient() {
            OkHttpClient client = new OkHttpClient();
            client.networkInterceptors().add(new StethoInterceptor());
            return client;
        }
    }
```

Here is the stacktrace:

```
03-11 12:49:48.675    4685-4906/fm.pause.debug E/AndroidRuntime﹕ FATAL EXCEPTION: StethoWorker30
    Process: fm.pause.debug, PID: 4685
    java.lang.OutOfMemoryError
            at java.lang.String.<init>(String.java:255)
            at java.lang.String.<init>(String.java:213)
            at java.io.ByteArrayOutputStream.toString(ByteArrayOutputStream.java:175)
            at com.facebook.stetho.inspector.network.ResponseBodyFileManager.readContentsAsUTF8(ResponseBodyFileManager.java:62)
            at com.facebook.stetho.inspector.network.ResponseBodyFileManager.readFile(ResponseBodyFileManager.java:52)
            at com.facebook.stetho.inspector.protocol.module.Network.readResponseBody(Network.java:69)
            at com.facebook.stetho.inspector.protocol.module.Network.getResponseBody(Network.java:54)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:89)
            at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60)
            at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:122)
            at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:104)
            at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:80)
            at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:169)
            at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:129)
            at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:39)
            at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:38)
            at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:147)
            at com.facebook.stetho.websocket.WebSocketHandler.handleSecured(WebSocketHandler.java:99)
            at com.facebook.stetho.server.SecureHttpRequestHandler.handle(SecureHttpRequestHandler.java:45)
            at org.apache.http.protocol.HttpService.doService(HttpService.java:243)
            at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:187)
            at com.facebook.stetho.server.LocalSocketHttpServer$WorkerThread.run(LocalSocketHttpServer.java:255)
```

I would really like to contribute so if you guys know where to point me at I'd be more than happy to issue a PR :)

**Comment by jasta** [comment]
I think you've found a bug in Stetho in the same way Stetho's found a bug in your code :)

The issue here is that due to the design of our JSON-RPC/WebSocket implementation, we require that all objects sent over the wire are first constructed as POJOs.  The DevTools protocol requires that we read network response bodies as a single, typically base64-encoded, UTF-8 string.  This means that in practice if the response body is a very large binary blob, the resulting base64 UTF-8 string will be so large that the VM will be unable to allocate it as a single contiguous char[] buffer*.

I suspect that rather than truly running out of memory, instead Dalvik/ART are refusing to allocate such a large buffer.  Somewhere in Logcat output this would be reflected, though it can be hard to spot sometimes.

This can be addressed by us in a couple of ways, but the more important question is: why are you downloading images that are likely much larger than the viewport size of the device?  Doing so wastes bandwidth and processing power locally, even with `BitmapFactory` downsampling the image during decoding.

* - Two important details conspire to inflate the size of this allocation: 1) char is 2 bytes in Java, and 2) base64 encoding typically increases data size by ~25%.  So, if your image was 1MB, you should expect an allocation of 2.5MB.

**Comment by fourlastor** [comment]
You're right, plugged in a Nexus 5 and I managed to find the culprit (with Stetho :) ).
I already proposed something like thumbor to reduce the image size as requested but currently it has low priority.

Just crashing like this isn't very clear tho, maybe something like logging an error if the content lenght is over a certain value (1MB should be good enough), without actually downloading it?

**Comment by jasta** [comment]
Agreed Stetho has the wrong behaviour.  It's supposed to help you debug these kinds of issues, not crash :)

I think we have two decent options:

1. Try to read the string, catch `OutOfMemoryException` and replace the contents with an error indicating this in some fashion.
2. Build a streaming API for our JSON-RPC encoder so that we can express potentially very large requests and responses (we have a couple other interesting places) in a streaming fashion for efficiency reasons.  I do really like this option, but unfortunately we hacked our way through a custom WebSocket and JSON-RPC implementation and neither are exactly well suited for this at the moment.

I'm inclined to post a quick diff for 1, then take a deeper look after 1.1.0 to see if we can rearchitect and improve our underlying protocol implementation.
